import type { Metadata } from "next";
import { Inria_Sans, Inria_Serif } from "next/font/google";
import { Provider } from "react";
import "./globals.css";
import { NavbarWithMegaMenu } from "./components/navbar";
import { Providers } from "./providers";
import HeaderLogo from "./components/header-logo";

const inriaSans = Inria_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  display: "swap",
  variable: "--font-inria-sans",
});
const inriaSerif = Inria_Serif({
  subsets: ["latin"],
  weight: ["700"],
  display: "swap",
  variable: "--font-inria-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inriaSans.variable} ${inriaSerif.variable}`}>
      <body className={`${inriaSans.variable} ${inriaSerif.variable}`}>
        {/* <div className="block w-full rounded-xl none backdrop-saturate-200 backdrop-blur-2xl bg-opacity-80 border border-white/80 bg-white text-white mx-auto max-w-screen-xl px-4 py-2"> */}
        <div className="flex flex-col items-center justify-between px-5 py-10 sm:px-20">
          <NavbarWithMegaMenu />
        </div>
        {/* </div> */}
        {children}
      </body>
    </html>
  );
}
